#!/bin/bash

# Simple justix installer

# Packet Tracer installer

installPacketTracer(){
    echo -e "\e[1m\e[95m  Downloading packet tracer \e[0m"

    echo -e "\e[\e[33m "

     axel -c -a -o /tmp/CiscoPacketTracer_801_Ubuntu_64bit.deb https://archive.org/download/cisco-packet-tracer-801-ubuntu-64bit/CiscoPacketTracer_801_Ubuntu_64bit.deb

    echo -e "\n \e[1m\e[95m Installing packet tracer...\n"

    gdebi -n /tmp/CiscoPacketTracer_801_Ubuntu_64bit.deb
    echo -e "\e[0m"

    echo -e "\n \e[1m\e[95m Done ! \n"



}

# Main Function

if [ $# -ne 2 ]; then
 echo -e "\e[1m\e[95m just needs two parameters  \e[0m"
 echo -e "\e[1m\e[95m Syntax: \e[0m"
 echo -e "\e[1m\e[95m    just install packettracer \e[0m"
 exit -1;
fi

if [ $1 == "install" ]
then
  case $2 in
      packettracer)
          installPacketTracer
          ;;
      *)
        echo -e "\e[1m\e[95m Unknown package \e[0m";
  esac

else
  echo -e "\e[1m\e[95m Just allowed install command "
fi



