#!/bin/sh
set -e
# Automatically added by dh_icons/12.1.1ubuntu1+p18.04+git20190517.0034
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/justix
fi
# End automatically added section
