title: Justix
subtitle: Ubuntu Mate for Ies El Just
description: >- # this means to ignore newlines until "baseurl:"
  Aci trobareu informació sobre la selecció de programari
  per a cicles a l'IES Jaume II El Just.
author: Departament d'informàtica de l'IES El Just
email: informatica.ieseljust@gmail.com
# avatar: assets/images/avatar.jpg
theme: jekyll-theme-cayman

